export const regionsData = [
    {
        id: 'central-core',
        name: 'Central Core',
        subtitle: 'Middle Volcano Ring',
        icon: 'whatshot',
        style: { top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
        colorClasses: {
            text: 'text-accent-red',
            bgSelect: 'bg-accent-red/20',
            bgHover: 'hover:bg-accent-red/10',
            border: 'border-accent-red',
            borderHover: 'hover:border-accent-red',
            borderOpacity: 'border-accent-red/30',
            gradTo: 'from-accent-red/100',
            gradToOpacity: 'from-accent-red/80',
            bgPing: 'bg-accent-red/60',
            bgDot: 'bg-accent-red',
            bgLine: 'bg-accent-red/80',
            bgLineOpacity: 'bg-accent-red/30',
        },
        hex: '#f87171',
        delay: '0s',
        animationClass: 'animate-float-slow',
        overview: 'The geothermic heart of the island ecosystem. The core continuously harvests kinetic and thermal energy from the massive volcanic ring.',
        challenges: 'High ambient temperature requires specialized cooling suits. Magma flow patterns are unstable.',
        simulation: 'Thermal efficiency: 84.2%. Output: 1.2 GW. Pressure monitoring active.',
        insights: 'Recent seismic readings indicate increased volcanic output near sub-sector B.',
        stats: { temp: '450°C', weather: 'Ash', pop: '0.2M' },
        status: 'WARNING',
        statusColor: 'bg-yellow-400',
        imageUrl: 'https://images.unsplash.com/photo-1614728514809-eb5b79d201c1?q=80&w=2670&auto=format&fit=crop'
    },
    {
        id: 'snow-mountain-west',
        name: 'Snow Mountain West',
        subtitle: 'Glacial Peak',
        icon: 'ac_unit',
        style: { top: '30%', left: '30%' },
        colorClasses: {
            text: 'text-white',
            bgSelect: 'bg-white/20',
            bgHover: 'hover:bg-white/10',
            border: 'border-white',
            borderHover: 'hover:border-white',
            borderOpacity: 'border-white/30',
            gradTo: 'from-white/100',
            gradToOpacity: 'from-white/80',
            bgPing: 'bg-white/60',
            bgDot: 'bg-white',
            bgLine: 'bg-white/80',
            bgLineOpacity: 'bg-white/30'
        },
        hex: '#ffffff',
        delay: '0.5s',
        animationClass: 'animate-float-medium',
        overview: 'Unforgiving, jagged mountains covered in eternal ice. Hosts advanced data centers requiring extreme cold environments.',
        challenges: 'Frequent blizzards disrupt comm relays. Permafrost degradation on western slopes.',
        simulation: 'Cooling capacity: 99.9%. Data sync latency: 12ms. Server load nominal.',
        insights: 'Ice core samples reveal pre-collapse atmospheric data patterns.',
        stats: { temp: '-30°C', weather: 'Snow', pop: '0.1M' },
        status: 'STABLE',
        statusColor: 'bg-blue-400',
        imageUrl: 'https://images.unsplash.com/photo-1548685913-fe6678babe8d?q=80&w=2618&auto=format&fit=crop'
    },
    {
        id: 'snow-mountain-east',
        name: 'Snow Mountain East',
        subtitle: 'High Altitude Observatory',
        icon: 'radar',
        style: { top: '30%', right: '30%' },
        colorClasses: {
            text: 'text-slate-300',
            bgSelect: 'bg-slate-300/20',
            bgHover: 'hover:bg-slate-300/10',
            border: 'border-slate-300',
            borderHover: 'hover:border-slate-300',
            borderOpacity: 'border-slate-300/30',
            gradTo: 'from-slate-300/100',
            gradToOpacity: 'from-slate-300/80',
            bgPing: 'bg-slate-300/60',
            bgDot: 'bg-slate-300',
            bgLine: 'bg-slate-300/80',
            bgLineOpacity: 'bg-slate-300/30'
        },
        hex: '#cbd5e1',
        delay: '1.2s',
        animationClass: 'animate-float-medium',
        overview: 'A high-altitude scientific sector where atmospheric anomalies are constant. The primary orbital observation deck is located here.',
        challenges: 'High altitude sickness risk for personnel. Electro-magnetic interference is common.',
        simulation: 'Orbital array tracking 4,201 objects. Signal interference: 14%.',
        insights: 'A new deep-space signal has been intercepted by array alpha-7.',
        stats: { temp: '-15°C', weather: 'Clear', pop: '0.5M' },
        status: 'ONLINE',
        statusColor: 'bg-green-500',
        imageUrl: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2670&auto=format&fit=crop'
    },
    {
        id: 'desert-south',
        name: 'Desert South',
        subtitle: 'Arid Zone // ruins',
        icon: 'wb_sunny',
        style: { bottom: '25%', left: '50%', transform: 'translate(-50%, 0)' },
        colorClasses: {
            text: 'text-accent-amber',
            bgSelect: 'bg-accent-amber/20',
            bgHover: 'hover:bg-accent-amber/10',
            border: 'border-accent-amber',
            borderHover: 'hover:border-accent-amber',
            borderOpacity: 'border-accent-amber/30',
            gradTo: 'from-accent-amber/100',
            gradToOpacity: 'from-accent-amber/80',
            bgPing: 'bg-accent-amber/60',
            bgDot: 'bg-accent-amber',
            bgLine: 'bg-accent-amber/80',
            bgLineOpacity: 'bg-accent-amber/30'
        },
        hex: '#fbbf24',
        delay: '1.5s',
        animationClass: 'animate-float-slow',
        overview: 'An expansive wasteland of shifting sands and ruins of the old world. Under the dunes lie ancient tech artifacts waiting to be uncovered.',
        challenges: 'Sandstorms compromise tech equipment. Scavenger raids are frequent.',
        simulation: 'Excavation progress: 34%. Relics recovered: 12. Defense grid: 80%.',
        insights: 'Ground-penetrating radar shows a massive metallic structure 40m below Sector 9.',
        stats: { temp: '45°C', weather: 'Clear', pop: '0.8M' },
        status: 'HEAT',
        statusColor: 'bg-amber-500',
        imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?q=80&w=2676&auto=format&fit=crop'
    },
    {
        id: 'forest-north',
        name: 'Forest North',
        subtitle: 'Elder Woods',
        icon: 'forest',
        style: { top: '20%', left: '50%', transform: 'translate(-50%, 0)' },
        colorClasses: {
            text: 'text-accent-green',
            bgSelect: 'bg-accent-green/20',
            bgHover: 'hover:bg-accent-green/10',
            border: 'border-accent-green',
            borderHover: 'hover:border-accent-green',
            borderOpacity: 'border-accent-green/30',
            gradTo: 'from-accent-green/100',
            gradToOpacity: 'from-accent-green/80',
            bgPing: 'bg-accent-green/60',
            bgDot: 'bg-accent-green',
            bgLine: 'bg-accent-green/80',
            bgLineOpacity: 'bg-accent-green/30'
        },
        hex: '#4ade80',
        delay: '2s',
        animationClass: 'animate-float-slow',
        overview: 'A mysterious and dense bio-luminescent forest serving as the island\'s lungs. The flora here is hyper-evolved.',
        challenges: 'Rapid toxic spore blooms. Navigation systems fail due to dense canopy.',
        simulation: 'O2 Generation: 110%. Biomass stability: nominal. Local fauna aggressive.',
        insights: 'A new glowing plant species has begun rapidly terraforming the northern edge.',
        stats: { temp: '18°C', weather: 'Humid', pop: 'Unknown' },
        status: 'UNKNOWN',
        statusColor: 'bg-purple-500',
        imageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?q=80&w=2680&auto=format&fit=crop'
    },
    {
        id: 'tech-harbor',
        name: 'Tech Harbor',
        subtitle: 'Bottom City Hub',
        icon: 'apartment',
        style: { bottom: '15%', right: '35%' },
        colorClasses: {
            text: 'text-primary',
            bgSelect: 'bg-primary/20',
            bgHover: 'hover:bg-primary/10',
            border: 'border-primary',
            borderHover: 'hover:border-primary',
            borderOpacity: 'border-primary/30',
            gradTo: 'from-primary/100',
            gradToOpacity: 'from-primary/80',
            bgPing: 'bg-primary/60',
            bgDot: 'bg-primary',
            bgLine: 'bg-primary/80',
            bgLineOpacity: 'bg-primary/30'
        },
        hex: '#6366f1',
        delay: '0.8s',
        animationClass: 'animate-float-medium',
        overview: 'The sprawling technological capital and naval hub connecting the outer islands to the central grid.',
        challenges: 'Overpopulation taxes the grid. Smuggling through the naval ports.',
        simulation: 'Grid load: 92%. Trade volume: 14k units/hr. Security alerts: 3.',
        insights: 'Black market cybernetics flowing through docks have increased by 15% this week.',
        stats: { temp: '22°C', weather: 'Rain', pop: '14.2M' },
        status: 'ONLINE',
        statusColor: 'bg-green-500',
        imageUrl: 'https://images.unsplash.com/photo-1515865644861-8ab4e5addf19?q=80&w=2670&auto=format&fit=crop'
    },
    {
        id: 'coastal-isles',
        name: 'Coastal Isles',
        subtitle: 'Water Reserves',
        icon: 'waves',
        style: { bottom: '30%', left: '20%' },
        colorClasses: {
            text: 'text-accent-cyan',
            bgSelect: 'bg-accent-cyan/20',
            bgHover: 'hover:bg-accent-cyan/10',
            border: 'border-accent-cyan',
            borderHover: 'hover:border-accent-cyan',
            borderOpacity: 'border-accent-cyan/30',
            gradTo: 'from-accent-cyan/100',
            gradToOpacity: 'from-accent-cyan/80',
            bgPing: 'bg-accent-cyan/60',
            bgDot: 'bg-accent-cyan',
            bgLine: 'bg-accent-cyan/80',
            bgLineOpacity: 'bg-accent-cyan/30'
        },
        hex: '#22d3ee',
        delay: '2.2s',
        animationClass: 'animate-float-medium',
        overview: 'A secluded sanctuary holding the purest water reserves and aquaculture farms, heavily guarded by automated drones.',
        challenges: 'Tidal instability and unpredictable mega-storms from the deep ocean.',
        simulation: 'Water purity: 99%. Desalination: 1.2M L/hr. Fishery output: stable.',
        insights: 'Deep sea drones picked up massive biological movement at 5000m depth.',
        stats: { temp: '24°C', weather: 'Clear', pop: '2.1M' },
        status: 'RESTRICTED',
        statusColor: 'bg-red-500',
        imageUrl: 'https://images.unsplash.com/photo-1495584816685-4bdbf1b5057e?q=80&w=2574&auto=format&fit=crop'
    }
];
